"""Build the Isaac Sim USD for the NAO from the vendored upstream URDF.

Two build steps, both producing untracked artifacts under ``assets/generated/nao``:

1. :func:`build_derived_urdf` rewrites the ROS ``package://`` mesh references of
   the verbatim upstream URDF into repository-relative filesystem paths, so
   Isaac Sim resolves the geometry with no ROS runtime, no ``ROS_PACKAGE_PATH``
   and no catkin workspace. It also drops the ``<gazebo>`` and
   ``<transmission>`` elements, which describe Gazebo plugins and ROS control
   transmissions that mean nothing in Isaac Sim.

   No physical quantity is touched: links, joints, inertials, limits, axes,
   visual and collision geometry and the ``scale="0.1 0.1 0.1"`` mesh factor are
   all passed through unchanged.

2. :func:`convert_nao_urdf_to_usd` runs the Isaac Lab :class:`UrdfConverter`,
   which wraps the ``isaacsim.asset.importer.urdf`` extension, to produce a USD
   that PhysX can instantiate as an articulation.

Importing this module does not require Isaac Lab; only calling the conversion
does. See ``third_party/nao/README.md`` for provenance and licensing.
"""

from __future__ import annotations

import os
import shutil
import xml.etree.ElementTree as ET
from pathlib import Path

from .nao_paths import (
    DERIVED_URDF_PATH,
    GENERATED_NAO_DIR,
    NAO_ASSET_DIR,
    NAO_URDF_PATH,
    NAO_USD_PATH,
    URDF_MESH_PACKAGE_PREFIX,
    describe_missing_meshes,
    meshes_are_available,
)

__all__ = [
    "build_derived_urdf",
    "convert_nao_urdf_to_usd",
    "ensure_nao_usd",
    "STRIPPED_ELEMENTS",
    "GENERATED_MESH_DIR",
]

STRIPPED_ELEMENTS = ("gazebo", "transmission")
"""Root-level elements removed from the derived URDF (Gazebo / ROS control only)."""

GENERATED_MESH_DIR = GENERATED_NAO_DIR / "meshes"
"""Holds byte-identical copies of meshes whose filename is illegal in USD.

The upstream collision meshes are named ``<Link>_0.10.stl``. The URDF importer
turns a mesh filename into a USD prim name, and a ``.`` cannot appear in an
``SdfPath`` identifier, so importing them directly aborts with
``Ill-formed SdfPath </colliders/base_link/Torso_0.10>`` and then
``RuntimeError: Used null prim``.

Copies are therefore made under this directory with the dot replaced by an
underscore. Only the *filename* changes: the file contents are copied byte for
byte, so the upstream geometry itself is never altered.
"""

_ATTRIBUTION = """
<!-- ===================================================================== -->
<!-- DERIVED FILE - GENERATED BY THIS PROJECT, DO NOT EDIT BY HAND.        -->
<!--                                                                      -->
<!-- Generated from the verbatim upstream URDF:                           -->
<!--   assets/robots/nao/urdf/nao.urdf                                    -->
<!--                                                                      -->
<!-- Upstream project : ros-naoqi/nao_robot (package nao_description)     -->
<!-- Upstream commit  : 67476469a1371b00b17538eb6ea336367ece7d44          -->
<!-- Original authors : Armin Hornung, Stefan Osswald                     -->
<!-- Copyright (c) 2009-2013, A. Hornung, University of Freiburg          -->
<!-- All rights reserved.                                                 -->
<!-- Licensed under the BSD 3-Clause License; the full text is at         -->
<!--   third_party/nao/LICENSE.nao_robot.txt                              -->
<!--                                                                      -->
<!-- Changes applied to the upstream file, and nothing else:              -->
<!--   1. package://nao_meshes/... mesh references rewritten to paths     -->
<!--      relative to this file, so Isaac Sim resolves them without ROS.  -->
<!--   2. <gazebo> and <transmission> elements removed (Gazebo plugins    -->
<!--      and ROS control transmissions, meaningless in Isaac Sim).       -->
<!--   3. Collision meshes named <Link>_0.10.stl point at byte-identical  -->
<!--      copies renamed to <Link>_0_10.stl, because a '.' is illegal in  -->
<!--      a USD prim name and aborts the import. Contents are unchanged.  -->
<!-- No link, joint, inertial, mass, limit, axis, collision or mesh       -->
<!-- scale value was modified.                                            -->
<!--                                                                      -->
<!-- The referenced .dae/.stl geometry is NOT covered by the BSD license  -->
<!-- above: it is Aldebaran / SoftBank Robotics material under            -->
<!-- CC BY-NC-ND 4.0. See third_party/nao/README.md.                      -->
<!-- ===================================================================== -->
"""


def _split_preamble(raw_urdf: str) -> str:
    """Return everything before the ``<robot>`` element (declaration + comments).

    ``ElementTree`` discards comments that sit outside the root element, so the
    upstream header is carried over as raw text instead.
    """
    index = raw_urdf.find("<robot")
    if index < 0:
        raise ValueError(f"No <robot> element found in {NAO_URDF_PATH}")
    return raw_urdf[:index].rstrip()


def _as_relative(target: Path) -> str:
    """Express ``target`` relative to the derived URDF, with forward slashes."""
    return os.path.relpath(target, GENERATED_NAO_DIR).replace(os.sep, "/")


def _resolve_mesh_reference(package_relative: str) -> tuple[str, bool]:
    """Return the path the derived URDF should use for one upstream mesh.

    A mesh whose stem contains ``.`` cannot become a USD prim name, so a
    byte-identical copy with a sanitized filename is placed in
    :data:`GENERATED_MESH_DIR` and referenced instead.

    Returns:
        The reference to write into the URDF, and whether a copy was needed.
    """
    source = NAO_ASSET_DIR / Path(package_relative)
    if "." not in source.stem:
        return _as_relative(source), False

    target = GENERATED_MESH_DIR / f"{source.stem.replace('.', '_')}{source.suffix}"
    target.parent.mkdir(parents=True, exist_ok=True)
    if not target.is_file() or target.stat().st_mtime < source.stat().st_mtime:
        shutil.copy2(source, target)
    return _as_relative(target), True


def build_derived_urdf(force: bool = False) -> Path:
    """Generate the Isaac-resolvable URDF. Returns its path.

    Args:
        force: Rebuild even when the derived file is newer than the source.

    Raises:
        FileNotFoundError: if the vendored URDF is absent.
        RuntimeError: if the NAO meshes have not been fetched yet.
    """
    if not NAO_URDF_PATH.is_file():
        raise FileNotFoundError(f"Vendored NAO URDF not found: {NAO_URDF_PATH}")
    if not meshes_are_available():
        raise RuntimeError(describe_missing_meshes())

    if (
        not force
        and DERIVED_URDF_PATH.is_file()
        and DERIVED_URDF_PATH.stat().st_mtime >= NAO_URDF_PATH.stat().st_mtime
    ):
        return DERIVED_URDF_PATH

    raw = NAO_URDF_PATH.read_text(encoding="utf-8")
    preamble = _split_preamble(raw)
    root = ET.fromstring(raw)

    for tag in STRIPPED_ELEMENTS:
        for element in root.findall(tag):
            root.remove(element)

    rewritten = 0
    sanitized = 0
    for mesh in root.iter("mesh"):
        filename = mesh.get("filename", "")
        if not filename.startswith(URDF_MESH_PACKAGE_PREFIX):
            continue
        package_relative = filename[len(URDF_MESH_PACKAGE_PREFIX) :]
        source = NAO_ASSET_DIR / Path(package_relative)
        if not source.is_file():
            raise RuntimeError(f"Mesh referenced by the URDF is missing: {source}")
        reference, was_copied = _resolve_mesh_reference(package_relative)
        mesh.set("filename", reference)
        rewritten += 1
        sanitized += int(was_copied)

    remaining = [
        mesh.get("filename", "")
        for mesh in root.iter("mesh")
        if mesh.get("filename", "").startswith("package://")
    ]
    if remaining:
        raise RuntimeError(f"Unresolved package:// references remain: {sorted(set(remaining))}")

    ET.indent(root, space="  ")
    body = ET.tostring(root, encoding="unicode")

    DERIVED_URDF_PATH.parent.mkdir(parents=True, exist_ok=True)
    DERIVED_URDF_PATH.write_text(
        f"{preamble}\n{_ATTRIBUTION.strip()}\n{body}\n", encoding="utf-8"
    )
    print(
        f"[nao] derived URDF written: {DERIVED_URDF_PATH}\n"
        f"[nao]   {rewritten} mesh paths resolved, "
        f"{sanitized} copied with USD-legal filenames"
    )
    return DERIVED_URDF_PATH


def convert_nao_urdf_to_usd(force: bool = False) -> Path:
    """Convert the derived URDF to USD with the Isaac Lab URDF converter.

    Must be called after the Isaac Sim application has been launched, because
    the converter drives the ``isaacsim.asset.importer.urdf`` extension.

    Converter options are deliberately conservative:

    * ``fix_base=False`` — the robot is free-floating, not welded to the world.
    * ``merge_fixed_joints=True`` — collapses only the 36 *fixed* frames of the
      URDF (cameras, sonars, FSRs, bumpers, IMU, tactile, soles). 27 of them
      carry no ``<inertial>`` at all, so keeping them would hand PhysX
      zero-mass bodies. No joint with a degree of freedom is merged away.
    * ``joint_drive`` with ``target_type="none"`` and zero gains — the robot has
      no controller in this phase, so every joint is left passive and the robot
      is expected to collapse under gravity. That is the point here: it
      validates the articulation, not locomotion.

      This has to be stated explicitly. Leaving ``joint_drive=None`` does *not*
      fall back to the URDF, which declares no ``<dynamics>`` at all: it leaves
      the importer's own default of stiffness 35810 with **zero damping** on
      every joint. An undamped stiff spring on the 2e-6 kg finger links makes
      the articulation diverge within a few hundred steps. Zero gains both
      avoid inventing a controller and keep the solver well conditioned.
    * ``collider_type="convex_hull"`` and ``self_collision=False`` — Isaac Lab
      defaults, left alone.

    Returns:
        Path to the generated USD file.
    """
    from isaaclab.sim.converters import UrdfConverter, UrdfConverterCfg

    urdf_path = build_derived_urdf(force=force)

    cfg = UrdfConverterCfg(
        asset_path=str(urdf_path),
        usd_dir=str(NAO_USD_PATH.parent),
        usd_file_name=NAO_USD_PATH.name,
        force_usd_conversion=force,
        make_instanceable=False,
        fix_base=False,
        merge_fixed_joints=True,
        convert_mimic_joints_to_normal_joints=True,
        collider_type="convex_hull",
        self_collision=False,
        joint_drive=UrdfConverterCfg.JointDriveCfg(
            drive_type="force",
            target_type="none",
            gains=UrdfConverterCfg.JointDriveCfg.PDGainsCfg(stiffness=0.0, damping=0.0),
        ),
    )
    converter = UrdfConverter(cfg)
    usd_path = Path(converter.usd_path)
    print(f"[nao] USD available at: {usd_path}")
    return usd_path


def ensure_nao_usd(force: bool = False) -> Path:
    """Return the NAO USD path, generating it on first use."""
    if not force and NAO_USD_PATH.is_file():
        return NAO_USD_PATH
    return convert_nao_urdf_to_usd(force=force)
