runner:
  algorithm: PPO
  num_steps_per_env: 24
  max_iterations: 10000
  save_interval: 200

policy:
  actor_hidden_dims: [512, 256, 128]
  critic_hidden_dims: [512, 256, 128]
  activation: elu

ppo:
  learning_rate: 0.0003
  entropy_coef: 0.01
  num_learning_epochs: 5
  num_mini_batches: 4
  gamma: 0.99
  lam: 0.95
