"""Fully computable linear-mechanical LQR surrogate.

The surrogate compares unconstrained linear system identification with a
projection onto semi-implicit Euler dynamics generated by an SPD mass matrix,
an SPD stiffness matrix, and diagonal non-negative damping.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

import numpy as np
from scipy.linalg import solve_discrete_are, solve_discrete_lyapunov
from scipy.optimize import least_squares


@dataclass(frozen=True)
class MechanicalSystem:
    dof: int
    dt: float
    mass: np.ndarray
    stiffness: np.ndarray
    damping: np.ndarray
    a: np.ndarray
    b: np.ndarray
    q_cost: np.ndarray
    r_cost: np.ndarray


def _chain_laplacian(dof: int) -> np.ndarray:
    laplacian = np.zeros((dof, dof))
    for index in range(dof - 1):
        laplacian[index, index] += 1.0
        laplacian[index + 1, index + 1] += 1.0
        laplacian[index, index + 1] -= 1.0
        laplacian[index + 1, index] -= 1.0
    return laplacian


def discretize_mechanics(
    mass: np.ndarray, stiffness: np.ndarray, damping: np.ndarray, dt: float
) -> tuple[np.ndarray, np.ndarray]:
    """Semi-implicit Euler matrices for ``M qdd + D qd + K q = u``."""
    dof = mass.shape[0]
    identity = np.eye(dof)
    mass_inv = np.linalg.inv(mass)
    mass_inv_k = mass_inv @ stiffness
    mass_inv_d = mass_inv @ damping

    a = np.block(
        [
            [identity - dt**2 * mass_inv_k, dt * (identity - dt * mass_inv_d)],
            [-dt * mass_inv_k, identity - dt * mass_inv_d],
        ]
    )
    b = np.vstack((dt**2 * mass_inv, dt * mass_inv))
    return a, b


def make_mechanical_system(dof: int = 2, dt: float = 0.05) -> MechanicalSystem:
    """Construct a stable coupled mass-spring-damper benchmark."""
    laplacian = _chain_laplacian(dof)
    mass = np.diag(1.0 + 0.15 * np.arange(dof)) + 0.04 * laplacian
    stiffness = 1.5 * np.eye(dof) + 0.35 * laplacian
    damping = np.diag(0.18 + 0.03 * np.arange(dof))
    a, b = discretize_mechanics(mass, stiffness, damping, dt)
    q_cost = np.diag(np.concatenate((10.0 * np.ones(dof), np.ones(dof))))
    r_cost = 0.1 * np.eye(dof)
    return MechanicalSystem(
        dof=dof,
        dt=dt,
        mass=mass,
        stiffness=stiffness,
        damping=damping,
        a=a,
        b=b,
        q_cost=q_cost,
        r_cost=r_cost,
    )


def lqr_gain(a: np.ndarray, b: np.ndarray, q: np.ndarray, r: np.ndarray) -> np.ndarray:
    """Return the infinite-horizon discrete LQR gain for ``u=-Kx``."""
    p = solve_discrete_are(a, b, q, r)
    return np.linalg.solve(r + b.T @ p @ b, b.T @ p @ a)


def lqr_cost(
    a_true: np.ndarray,
    b_true: np.ndarray,
    gain: np.ndarray,
    q: np.ndarray,
    r: np.ndarray,
    initial_covariance: np.ndarray | None = None,
) -> float:
    """Evaluate a controller on the true system from a Gaussian initial state."""
    closed_loop = a_true - b_true @ gain
    if np.max(np.abs(np.linalg.eigvals(closed_loop))) >= 1.0:
        return float("inf")
    stage_cost = q + gain.T @ r @ gain
    value = solve_discrete_lyapunov(closed_loop.T, stage_cost)
    covariance = (
        np.eye(a_true.shape[0]) if initial_covariance is None else initial_covariance
    )
    return float(np.trace(value @ covariance))


def sample_transitions(
    system: MechanicalSystem,
    n_samples: int,
    rng: np.random.Generator,
    noise_std: float = 0.01,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Sample persistently exciting one-step transitions."""
    state = rng.normal(scale=0.7, size=(n_samples, 2 * system.dof))
    action = rng.normal(scale=1.0, size=(n_samples, system.dof))
    next_state = state @ system.a.T + action @ system.b.T
    next_state += rng.normal(scale=noise_std, size=next_state.shape)
    return state, action, next_state


def fit_unstructured(
    state: np.ndarray,
    action: np.ndarray,
    next_state: np.ndarray,
    ridge: float = 1e-8,
) -> tuple[np.ndarray, np.ndarray]:
    """Ridge-fit unrestricted discrete matrices ``(A,B)``."""
    design = np.concatenate((state, action), axis=1)
    gram = design.T @ design + ridge * np.eye(design.shape[1])
    coefficients = np.linalg.solve(gram, design.T @ next_state)
    state_dim = state.shape[1]
    return coefficients[:state_dim].T, coefficients[state_dim:].T


def _project_spd(matrix: np.ndarray, floor: float = 1e-5) -> np.ndarray:
    symmetric = 0.5 * (matrix + matrix.T)
    eigenvalues, eigenvectors = np.linalg.eigh(symmetric)
    return (eigenvectors * np.maximum(eigenvalues, floor)) @ eigenvectors.T


def project_to_mechanics(
    a: np.ndarray, b: np.ndarray, dof: int, dt: float
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """Project unrestricted matrices to SPD ``M,K`` and diagonal ``D``."""
    identity = np.eye(dof)
    a_qq = a[:dof, :dof]
    a_qv = a[:dof, dof:]
    a_vq = a[dof:, :dof]
    a_vv = a[dof:, dof:]
    b_q = b[:dof]
    b_v = b[dof:]

    mass_inv = _project_spd(0.5 * (b_v / dt + b_q / dt**2))
    mass = np.linalg.inv(mass_inv)

    stiffness_from_velocity = -mass @ a_vq / dt
    stiffness_from_position = mass @ (identity - a_qq) / dt**2
    stiffness = _project_spd(
        0.5 * (stiffness_from_velocity + stiffness_from_position)
    )

    damping_from_velocity = mass @ (identity - a_vv) / dt
    damping_from_position = mass @ (identity - a_qv / dt) / dt
    damping_diagonal = np.maximum(
        np.diag(0.5 * (damping_from_velocity + damping_from_position)), 1e-5
    )
    damping = np.diag(damping_diagonal)

    a_structured, b_structured = discretize_mechanics(
        mass, stiffness, damping, dt
    )
    return a_structured, b_structured, mass, stiffness, damping


def _pack_spd(matrix: np.ndarray) -> np.ndarray:
    rows, columns = np.tril_indices(matrix.shape[0])
    factor = np.linalg.cholesky(_project_spd(matrix))
    packed = factor[rows, columns].copy()
    diagonal = rows == columns
    packed[diagonal] = np.log(packed[diagonal])
    return packed


def _unpack_spd(parameters: np.ndarray, dof: int) -> np.ndarray:
    rows, columns = np.tril_indices(dof)
    factor = np.zeros((dof, dof))
    entries = parameters.copy()
    diagonal = rows == columns
    entries[diagonal] = np.exp(entries[diagonal])
    factor[rows, columns] = entries
    return factor @ factor.T


def _pack_mechanics(
    mass: np.ndarray, stiffness: np.ndarray, damping: np.ndarray
) -> np.ndarray:
    return np.concatenate(
        (
            _pack_spd(mass),
            _pack_spd(stiffness),
            np.log(np.maximum(np.diag(damping), 1e-7)),
        )
    )


def _unpack_mechanics(
    parameters: np.ndarray, dof: int
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    symmetric = dof * (dof + 1) // 2
    mass = _unpack_spd(parameters[:symmetric], dof)
    stiffness = _unpack_spd(parameters[symmetric : 2 * symmetric], dof)
    damping = np.diag(np.exp(parameters[2 * symmetric :]))
    return mass, stiffness, damping


def fit_structured_mechanics(
    state: np.ndarray,
    action: np.ndarray,
    next_state: np.ndarray,
    *,
    dof: int,
    dt: float,
    a_initial: np.ndarray | None = None,
    b_initial: np.ndarray | None = None,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """Fit the lower-dimensional mechanical class by constrained least squares."""
    nominal = _pack_mechanics(
        np.eye(dof), np.eye(dof), 0.1 * np.eye(dof)
    )
    candidates = [nominal]
    if a_initial is not None and b_initial is not None:
        try:
            _, _, mass, stiffness, damping = project_to_mechanics(
                a_initial, b_initial, dof, dt
            )
            candidates.append(_pack_mechanics(mass, stiffness, damping))
        except np.linalg.LinAlgError:
            pass

    def residual(parameters: np.ndarray) -> np.ndarray:
        mass, stiffness, damping = _unpack_mechanics(parameters, dof)
        a_hat, b_hat = discretize_mechanics(mass, stiffness, damping, dt)
        prediction = state @ a_hat.T + action @ b_hat.T
        return (prediction - next_state).ravel()

    initial = min(candidates, key=lambda value: np.linalg.norm(residual(value)))
    symmetric = dof * (dof + 1) // 2
    lower = np.full(2 * symmetric + dof, -10.0)
    upper = np.full(2 * symmetric + dof, 10.0)
    rows, columns = np.tril_indices(dof)
    diagonal_positions = np.nonzero(rows == columns)[0]
    lower[diagonal_positions] = -7.0
    upper[diagonal_positions] = 5.0
    lower[symmetric + diagonal_positions] = -7.0
    upper[symmetric + diagonal_positions] = 5.0
    lower[2 * symmetric :] = -7.0
    upper[2 * symmetric :] = 3.0
    initial = np.clip(initial, lower + 1e-9, upper - 1e-9)

    fitted = least_squares(
        residual,
        initial,
        bounds=(lower, upper),
        max_nfev=500,
        x_scale="jac",
    )
    mass, stiffness, damping = _unpack_mechanics(fitted.x, dof)
    a_structured, b_structured = discretize_mechanics(
        mass, stiffness, damping, dt
    )
    return a_structured, b_structured, mass, stiffness, damping


def structured_parameter_count(dof: int) -> int:
    """Free parameters in symmetric ``M,K`` plus diagonal ``D``."""
    symmetric = dof * (dof + 1) // 2
    return 2 * symmetric + dof


def unstructured_parameter_count(dof: int) -> int:
    """Free parameters in unrestricted ``A in R^(2d x 2d), B in R^(2d x d)``."""
    return 6 * dof * dof


def run_lqr_surrogate(
    *,
    dof: int = 2,
    sample_sizes: tuple[int, ...] = (32, 64, 128, 256),
    seeds: tuple[int, ...] = tuple(range(10)),
    dt: float = 0.05,
    noise_std: float = 0.01,
) -> dict[str, Any]:
    """Run the complete identification-to-control comparison."""
    system = make_mechanical_system(dof=dof, dt=dt)
    optimal_gain = lqr_gain(system.a, system.b, system.q_cost, system.r_cost)
    optimal_cost = lqr_cost(
        system.a, system.b, optimal_gain, system.q_cost, system.r_cost
    )
    rows: list[dict[str, float | int]] = []

    for n_samples in sample_sizes:
        metrics: dict[str, list[float]] = {
            "unstructured_gap": [],
            "structured_gap": [],
            "unstructured_error": [],
            "structured_error": [],
        }
        stable = {"unstructured": 0, "structured": 0}
        for seed in seeds:
            rng = np.random.default_rng(seed)
            state, action, next_state = sample_transitions(
                system, n_samples, rng, noise_std
            )
            a_free, b_free = fit_unstructured(state, action, next_state)
            a_struct, b_struct, _, _, _ = fit_structured_mechanics(
                state,
                action,
                next_state,
                dof=dof,
                dt=dt,
                a_initial=a_free,
                b_initial=b_free,
            )

            scale = np.linalg.norm(system.a) + np.linalg.norm(system.b)
            metrics["unstructured_error"].append(
                (np.linalg.norm(a_free - system.a) + np.linalg.norm(b_free - system.b))
                / scale
            )
            metrics["structured_error"].append(
                (
                    np.linalg.norm(a_struct - system.a)
                    + np.linalg.norm(b_struct - system.b)
                )
                / scale
            )

            for name, a_hat, b_hat in (
                ("unstructured", a_free, b_free),
                ("structured", a_struct, b_struct),
            ):
                try:
                    gain = lqr_gain(a_hat, b_hat, system.q_cost, system.r_cost)
                    cost = lqr_cost(
                        system.a, system.b, gain, system.q_cost, system.r_cost
                    )
                except (ValueError, np.linalg.LinAlgError):
                    cost = float("inf")
                if np.isfinite(cost):
                    stable[name] += 1
                    metrics[f"{name}_gap"].append((cost - optimal_cost) / optimal_cost)

        row: dict[str, float | int] = {"n_samples": n_samples}
        for name in ("unstructured", "structured"):
            gaps = np.asarray(metrics[f"{name}_gap"])
            errors = np.asarray(metrics[f"{name}_error"])
            row[f"{name}_relative_cost_gap"] = (
                float(np.mean(gaps)) if gaps.size else float("inf")
            )
            row[f"{name}_dynamics_error"] = float(np.mean(errors))
            row[f"{name}_stability_rate"] = stable[name] / len(seeds)
        rows.append(row)

    structured_dim = structured_parameter_count(dof)
    unstructured_dim = unstructured_parameter_count(dof)
    return {
        "config": {
            "dof": dof,
            "dt": dt,
            "noise_std": noise_std,
            "sample_sizes": list(sample_sizes),
            "seeds": list(seeds),
        },
        "parameter_dimensions": {
            "structured": structured_dim,
            "unstructured": unstructured_dim,
            "kappa": unstructured_dim / structured_dim,
        },
        "optimal_cost": optimal_cost,
        "rows": rows,
    }
