#!/usr/bin/env python
"""Generate LaTeX constants from executable model-complexity calculations."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "src"))

from lagrangian_mbrl.theory import complexity_report  # noqa: E402


def _tex_int(value: int) -> str:
    return f"{value:,}".replace(",", "{,}")


def render_constants() -> str:
    report = complexity_report()
    values = {
        "TheoryDof": str(report.dof),
        "CholeskyEntries": str(report.cholesky_entries),
        "FullMassEntries": str(report.full_mass_entries),
        "DelanParameters": _tex_int(report.delan_parameters),
        "FullMassEnergyParameters": _tex_int(report.full_mass_energy_parameters),
        "DirectMlpParameters": _tex_int(report.direct_mlp_parameters),
        "EnsembleParameters": _tex_int(report.probabilistic_ensemble_parameters),
        "KappaOutput": f"{report.kappa_output:.2f}",
        "KappaCholeskyParameters": f"{report.kappa_cholesky_parameters:.2f}",
        "KappaDirectParameters": f"{report.kappa_direct_parameters:.2f}",
        "KappaEnsembleParameters": f"{report.kappa_ensemble_parameters:.2f}",
    }
    lines = [
        "% Generated by scripts/generate_theory_constants.py; do not edit.",
        *(f"\\newcommand{{\\{name}}}{{{value}}}" for name, value in values.items()),
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--out",
        type=Path,
        default=REPO_ROOT / "theory" / "generated" / "complexity_constants.tex",
    )
    args = parser.parse_args()
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(render_constants(), encoding="ascii")
    print(f"Wrote {args.out}")


if __name__ == "__main__":
    main()
