#!/usr/bin/env python
"""Run the computable LQR surrogate and emit JSON plus a LaTeX table."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "src"))

from lagrangian_mbrl.theory import run_lqr_surrogate  # noqa: E402


def _percent(value: float) -> str:
    return f"{100.0 * value:.2f}"


def render_constants(results: dict) -> str:
    dimensions = results["parameter_dimensions"]
    return "\n".join(
        [
            "% Generated by scripts/run_lqr_surrogate.py; do not edit.",
            f"\\newcommand{{\\LqrDof}}{{{results['config']['dof']}}}",
            f"\\newcommand{{\\LqrStructuredDimension}}{{{dimensions['structured']}}}",
            f"\\newcommand{{\\LqrUnstructuredDimension}}{{{dimensions['unstructured']}}}",
            f"\\newcommand{{\\LqrDimensionKappa}}{{{dimensions['kappa']:.2f}}}",
            "",
        ]
    )


def render_table(results: dict) -> str:
    lines = [
        "% Generated by scripts/run_lqr_surrogate.py; do not edit.",
        "\\begin{tabular}{rrrrr}",
        "\\toprule",
        "$N$ & free gap (\\%) & mech. gap (\\%) & free stable & mech. stable \\\\",
        "\\midrule",
    ]
    for row in results["rows"]:
        lines.append(
            f"{row['n_samples']} & "
            f"{_percent(row['unstructured_relative_cost_gap'])} & "
            f"{_percent(row['structured_relative_cost_gap'])} & "
            f"{_percent(row['unstructured_stability_rate'])}\\% & "
            f"{_percent(row['structured_stability_rate'])}\\% \\\\"
        )
    lines.extend(["\\bottomrule", "\\end{tabular}", ""])
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dof", type=int, default=2)
    parser.add_argument("--sample-sizes", type=int, nargs="+", default=[32, 64, 128, 256])
    parser.add_argument("--seeds", type=int, nargs="+", default=list(range(10)))
    parser.add_argument("--noise-std", type=float, default=0.01)
    parser.add_argument(
        "--out",
        type=Path,
        default=REPO_ROOT / "theory" / "generated" / "lqr_surrogate_results.json",
    )
    parser.add_argument(
        "--constants-out",
        type=Path,
        default=REPO_ROOT / "theory" / "generated" / "lqr_surrogate_constants.tex",
    )
    parser.add_argument(
        "--tex-out",
        type=Path,
        default=REPO_ROOT / "theory" / "generated" / "lqr_surrogate_table.tex",
    )
    args = parser.parse_args()

    results = run_lqr_surrogate(
        dof=args.dof,
        sample_sizes=tuple(args.sample_sizes),
        seeds=tuple(args.seeds),
        noise_std=args.noise_std,
    )
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(json.dumps(results, indent=2) + "\n", encoding="ascii")
    args.constants_out.write_text(render_constants(results), encoding="ascii")
    args.tex_out.write_text(render_table(results), encoding="ascii")
    print(json.dumps(results, indent=2))
    print(f"Wrote {args.out}")
    print(f"Wrote {args.constants_out}")
    print(f"Wrote {args.tex_out}")


if __name__ == "__main__":
    main()
